accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("password-change/", views.PasswordChange.as_view(), name="password_change"),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

api/urls.py
from django.urls import include, path

from rest_framework import routers

from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('categories', views.CategoryViewSet)
router.register('expenses', views.ExpensesViewSet)
router.register('incomes', views.IncomeViewSet)

user_categories_list = views.AllUserCategoriesViewSet.as_view({
    'get': 'list'
})
user_monthly_categories_list = views.AllUserMonthlyCategoriesViewSet.as_view({
    'get': 'list'
})
budget_info_list = views.BudgetInfoView.as_view({
    'get': 'retrieve'
})


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('user-categories/', user_categories_list, name='user-categories-list'),
    path('user-monthly-categories/', user_monthly_categories_list,
         name='user-monthly-categories-list'),
    path('budget-info/', budget_info_list, name='budget-info'),
]

expense_tracker/urls.py
"""expense_tracker URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense_tracker_app.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("api/", include('api.urls', namespace='api')),
]

expense_tracker_app/urls.py
from django.urls import include, path

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('budget/', views.BudgetView.as_view(), name='budget'),
    path('monhtly-expense-tracker/', views.MonthlyExpenseTrackerView.as_view(),
         name='monthly-expense-tracker'),
]

expense_tracker_app/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Sum
from django.utils import timezone


class Expense(models.Model):
    name = models.CharField('Name', max_length=20)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    cost = models.DecimalField('Cost', max_digits=9, decimal_places=2, validators=[
                               MinValueValidator(0.01)])
    day_due = models.IntegerField('Day Due',
                                  validators=[MaxValueValidator(31), MinValueValidator(1)], null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expected_cost = models.DecimalField('Expected Cost', max_digits=9, decimal_places=2, validators=[
                                        MinValueValidator(0.01)], null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('Name', max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    monthly = models.BooleanField(default=False)
    date = models.DateField(null=True, editable=False)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['user', 'pk']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        ''' 
        If date is given and monthly false, date field gets changed to None.
        Updates date field if monthly.
        '''
        if self.date and not self.monthly:
            self.date = None
        elif not self.id and self.monthly:
            self.date = timezone.localdate()
        return super(Category, self).save(*args, **kwargs)

    def get_sum_expenses_category(self):
        if self.expense_set.all():
            return self.expense_set.aggregate(Sum('cost'))['cost__sum']
        return 0


class Income(models.Model):

    class PaySchedule(models.IntegerChoices):
        MONTHLY = 0, 'Monthly'
        BI_MONTHLY = 1, 'Bi-Monthly'
        WEEKLY = 2, 'Weekly'
        BI_WEEKLY = 3, 'Bi-Weekly'

    net_income = models.DecimalField('Net Income',
                                     max_digits=9, decimal_places=2, default=0, validators=[
                                         MinValueValidator(0)])
    savings_percent = models.PositiveIntegerField('Savings Percent',
                                                  validators=[MaxValueValidator(100)], default=0)
    extra_income = models.DecimalField('Extra Monthly Income',
                                       max_digits=9, decimal_places=2, default=0, validators=[
                                           MinValueValidator(0)])
    pay_schedule = models.IntegerField('Pay Schedule',
                                       default=PaySchedule.MONTHLY, choices=PaySchedule.choices)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def get_total_monthly(self):
        if self.pay_schedule == self.PaySchedule.MONTHLY.value:
            return self.net_income + self.extra_income

        elif self.pay_schedule == self.PaySchedule.BI_MONTHLY.value:
            return round(((self.net_income + self.extra_income) / 2), 2)

        elif self.pay_schedule == self.PaySchedule.WEEKLY.value:
            return round(((self.net_income + self.extra_income) * 52 / 12), 2)

        elif self.pay_schedule == self.PaySchedule.BI_WEEKLY.value:
            return round(((self.net_income + self.extra_income) * 26 / 12), 2)

    def get_sum_expenses_user(self):
        expenses = Expense.objects.filter(
            user=self.user, category__monthly=False)
        if expenses:
            return expenses.aggregate(Sum('cost'))['cost__sum']
        return 0

    def get_sum_monthly_expenses_user(self):
        expenses = Expense.objects.filter(
            user=self.user, category__monthly=True)
        if expenses:
            return expenses.aggregate(Sum('cost'))['cost__sum']
        return 0

    def get_expenses_count(self):
        categories = Category.objects.filter(user=self.user, monthly=False)
        expenses_count = 0
        for expense in categories.values_list('expense', flat=True):
            expenses_count += 1 if expense else 0
        return expenses_count

    def get_monthly_savings(self):
        return round(self.get_total_monthly() * self.savings_percent / 100, 2)

    def get_monthly_spendable(self):
        return self.get_total_monthly() - self.get_sum_expenses_user() - self.get_monthly_savings()

    def get_daily_spendable(self):
        return round(self.get_monthly_spendable() * 12 / 365, 2)

    def get_month_left_money(self):
        return self.get_total_monthly() - self.get_sum_monthly_expenses_user() - self.get_monthly_savings()

expense_tracker_app/forms.py
from django import forms

from .models import Income


class IncomeForm(forms.ModelForm):

    class Meta:
        model = Income
        fields = '__all__'

expense_tracker_app/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views import View

from .forms import IncomeForm
from .models import Category, Expense, Income


class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        context = {}
        context['categories'] = Category.objects.filter(
            user=request.user, monthly=False)
        context['income'] = Income.objects.get(user=request.user)
        return render(request,
                      'expense_tracker_app/index.html',
                      context)


class BudgetView(LoginRequiredMixin, View):

    def get(self, request):
        context = {}
        context['categories'] = Category.objects.filter(
            user=request.user, monthly=False)
        context['expenses_count'] = request.user.income.get_expenses_count()
        context['income_form'] = IncomeForm()
        context['income'] = Income.objects.get(user=request.user)
        return render(request,
                      'expense_tracker_app/budget.html',
                      context)


class MonthlyExpenseTrackerView(LoginRequiredMixin, View):

    def get(self, request):
        context = {}
        context['categories'] = Category.objects.filter(
            user=request.user, monthly=True)
        context['income_form'] = IncomeForm()
        context['expenses'] = Expense.objects.filter(user=request.user)
        context['income'] = Income.objects.get(user=request.user)
        context['month'] = datetime.datetime.now().strftime('%B')
        return render(request,
                      'expense_tracker_app/monthly_expense_tracker.html',
                      context)

expense_tracker_app/templates/expense_tracker_app/base.html
{% load static %}
{% url 'index' as index_url %}
{% url 'budget' as budget_url %}
{% url 'monthly-expense-tracker' as monthly_expense_tracker %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Epxense Tracker | {% block title %}{% endblock title %}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  <!--Main style-->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {% block head_extra %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <nav class="main-header navbar navbar-expand navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" data-auto-collapse-size="1029" data-enable-remember="true"><i class="fa fa-bars"></i></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="{% static 'img/user-icon.png' %}" class="user-image img-circle elevation-2" alt="User Image">
          <span class="d-none d-md-inline">{{ user }}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- User image -->
          <li class="user-header bg-dark">
            <img src="{% static 'img/user-icon.png' %}" class="img-circle elevation-2" alt="User Image">

            <p>
              {{ user }}
              <small>Member since {{ user.date_joined|date:"M. Y" }}</small>
            </p>
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <a href="{% url 'accounts:password_change' %}" class="btn btn-default btn-flat btn-secondary">Change password</a>
            <a href="{% url 'accounts:logout' %}" class="btn btn-default btn-flat float-right">Sign out</a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-success elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'index' %}" class="brand-link navbar-success">
      <img src="{% static 'img/expense-tracker-app.png' %}" alt="Expense Tracker Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Expense Tracker</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="{{ index_url }}" class="nav-link {% if request.path == index_url %}active{% endif %}">
              <i class="nav-icon fas fa-wallet"></i>
              <p>Budget Summary</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ budget_url }}" class="nav-link {% if request.path == budget_url %}active{% endif %}">
              <i class="nav-icon fas fa-dollar-sign"></i>
              <p>Budget</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ monthly_expense_tracker }}" class="nav-link {% if request.path == monthly_expense_tracker %}active{% endif %}">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>Monthly Expense Tracker</p>
            </a>
          </li>
          {% if user.is_staff %}
          <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link">
              <i class="nav-icon fas fa-user-shield"></i>
              <p>Admin Site</p>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper px-4 py-2">
   <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <h1 class="m-0 text-dark">{% block header_title %}{% endblock %}</h1>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
          {% block content %}{% endblock  %}
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-inline">
      v1.0
    </div>
    <strong>Copyright &copy; 2020 <a href="{% url 'index' %}">Expense Tracker</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
{% block body_extra %}{% endblock %}
</body>
</html>

expense_tracker_app/templates/expense_tracker_app/index.html
{% extends 'expense_tracker_app/base.html' %}
{% load static %}
{% url 'budget' as budget_url %}
{% block title %}Budget Summary{% endblock %}
{% block active_page %}Budget Summary{% endblock %}
{% block header_title %}Budget Summary{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-success">
      <div class="inner">
        <h3>{{ income.get_daily_spendable }}<sup style="font-size: 20px">$</sup></h3>

        <p>Daily Spendable</p>
      </div>
      <div class="icon">
        <i class="fas fa-dollar-sign"></i>
      </div>
      <a href="{{ budget_url }}" class="small-box-footer">
        More info <i class="fas fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-indigo">
      <div class="inner">
        <h3>{{ income.get_monthly_spendable }}<sup style="font-size: 20px">$</sup></h3>

        <p>Monthly Spendable</p>
      </div>
      <div class="icon">
        <i class="fas fa-money-bill-wave"></i>
      </div>
      <a href="{{ budget_url }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-olive">
      <div class="inner">
        <h3>{{ income.get_monthly_savings }}<sup style="font-size: 20px">$</sup></h3>

        <p>Monthly Savings</p>
      </div>
      <div class="icon">
        <i class="fas fa-piggy-bank"></i>
      </div>
      <a href="{{ budget_url }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-danger">
      <div class="inner">
        <h3>{{ income.get_sum_expenses_user }}<sup style="font-size: 20px">$</sup></h3>

        <p>Monthly Expenses</p>
      </div>
      <div class="icon">
        <i class="fas fa-shopping-cart"></i>
      </div>
      <a href="{{ budget_url }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
</div>
<!-- /.row -->
<div class="row mb-2">
  <div class="col-sm-6">
    <div class="card card-teal">
      <div class="card-header">
        <h3 class="card-title">Expenses Chart</h3>
        <div class="card-tools">
          <!-- Collapse Button -->
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="chartjs-size-monitor">
          <div class="chartjs-size-monitor">
            <div class="chartjs-size-monitor-expand">
              <div class="">
              </div>
            </div>
          </div>
          <div class="chartjs-size-monitor-shrink">
            <div class="">
            </div>
          </div>
        </div>
        <canvas id="donutChart"
          style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 644px;"
          width="644" height="250" class="chartjs-render-monitor"></canvas>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
  <div class="col-sm-6">
    <div class="card card-orange">
      <div class="card-header">
        <h3 class="card-title">Monthly Balance</h3>
        <div class="card-tools">
          <!-- Collapse Button -->
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="chartjs-size-monitor">
          <div class="chartjs-size-monitor">
            <div class="chartjs-size-monitor-expand">
              <div class="">
              </div>
            </div>
          </div>
          <div class="chartjs-size-monitor-shrink">
            <div class="">
            </div>
          </div>
        </div>
        <canvas id="barChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 644px;" width="644" height="250" class="chartjs-render-monitor"></canvas>
      </div>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<div class="row mb-2">
  <div class="col-sm-12">
    <div class="card card-info">
      <div class="card-header">
        <h3 class="card-title">Expenses</h3>
        <div class="card-tools">
          <!-- Collapse Button -->
          <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
          </button>
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <div class="row">
        {% for category in categories %}
          <div class="col-xl-6">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title category-title" data-sum-expenses="{{ category.get_sum_expenses_category }}">{{ category }}</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <table class="table table-striped text-center">
                  <thead>
                    <tr>
                      <th style="width: 5%">#</th>
                      <th style="width: 45%">Title</th>
                      <th style="width: 35%">Cost</th>
                      <th style="width: 15%">Day due</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% if category.expense_set.all %}
                    {% for expense in category.expense_set.all %}
                      <tr>
                        <td>{{ forloop.counter }}.</td>
                        <td>{{ expense }}</td>
                        <td>{{ expense.cost|floatformat:"-2" }}$</td>
                        <td>{% if expense.day_due %}{{ expense.day_due }}{% endif %}</td>
                      </tr>
                    {% endfor %}
                    {% else %}
                      <tr>
                        <td></td>
                        <td>Empty</td>
                        <td></td>
                        <td></td>
                      </tr>
                    {% endif %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        {% endfor %}
        </div>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>
<input type="hidden" id="monthly-expenses" value="{{ income.get_sum_expenses_user }}">
<input type="hidden" id="monthly-income" value="{{ income.get_total_monthly}}">
{% endblock %}
{% block body_extra %}
<!--ChartJS -->
<script src="{% static 'adminlte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- jQuery UI-->
<script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}