accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("password-change/", views.PasswordChange.as_view(), name="password_change"),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

api/urls.py
from django.urls import include, path

from rest_framework import routers

from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('categories', views.CategoryViewSet)
router.register('expenses', views.ExpensesViewSet)
router.register('incomes', views.IncomeViewSet)

user_categories_list = views.AllUserCategoriesViewSet.as_view({
    'get': 'list'
})
user_monthly_categories_list = views.AllUserMonthlyCategoriesViewSet.as_view({
    'get': 'list'
})
budget_info_list = views.BudgetInfoView.as_view({
    'get': 'retrieve'
})


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('user-categories/', user_categories_list, name='user-categories-list'),
    path('user-monthly-categories/', user_monthly_categories_list,
         name='user-monthly-categories-list'),
    path('budget-info/', budget_info_list, name='budget-info'),
]

expense_tracker/urls.py
"""expense_tracker URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
"""
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense_tracker_app.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path("api/", include('api.urls', namespace='api')),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    terms = forms.BooleanField(required=True, error_messages={
                               'required': 'You must accept our privacy policy and terms.'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'terms')

    def clean_email(self):
        email = self.cleaned_data.get('email')

        # Check to see if any users already exist with this email.
        try:
            match = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('This email address is already in use.')

accounts/views.py
from urllib import request

from django.conf.urls import url
from django.contrib import messages
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View

from .forms import RegisterForm
from .tokens import account_activation_token


class RegisterView(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('index')
        form = RegisterForm()
        return render(request,
                      'accounts/register.html',
                      {'form': form})

    def post(self, request):
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Account activation.'
            message = render_to_string('accounts/email_verification.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.id)),
                'token': account_activation_token.make_token(user),
            })
            to_email = user.email
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            messages.success(
                request, 'Confirm your email address to complete registration.')
            form = RegisterForm()
            return render(request,
                          'accounts/register.html',
                          {'form': form})
        else:
            return render(request,
                          'accounts/register.html',
                          {'form': form})


class LoginView(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('index')
        form = AuthenticationForm()
        return render(request,
                      'accounts/login.html',
                      {'form': form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if not request.POST.get('remember'):
                request.session.set_expiry(0)
            if request.GET.get('next'):
                return redirect(request.GET['next'])
            else:
                return redirect('index')
        else:
            return render(request,
                          'accounts/login.html',
                          {'form': form})


class ForgotPasswordView(View):

    def get(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            # messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            # messages.error(request, 'Please correct the error below.')
            pass


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        message = ('Thank you for confirming your email address.'
                   '\nNow you can log in to your account.')
        return HttpResponse(message)
    else:
        message = 'The activation link is invalid!'
        return HttpResponse(message)


class PasswordChange(LoginRequiredMixin, View):

    def get(self, request):
        return render(request,
                      'accounts/password_change.html')

    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(
                request, 'Your password was successfully updated!')
            return render(request,
                          'accounts/password_change.html')
        else:
            return render(request,
                          'accounts/password_change.html',
                          {'form': form})

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Expense Tracker | {% block page_title%}{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
{% block body %}{% endblock %}
<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
</body>
</html>

accounts/templates/accounts/email_verification.html
{% autoescape off %}
Hi {{ user.first_name }},
Click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
If you don't think it's you please ignore this email.
{% endautoescape %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block page_title %}Log in{% endblock %}
{% block body %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index' %}"><b>Expense </b>Tracker</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          {% render_field form.username class="form-control" placeholder="Username" %}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          {% render_field form.password class="form-control" placeholder="Password" %}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
          <div class="row">
            <div class="col-12 text-danger">
              {{ error }}
            </div>
          </div>
          {% endfor %}
        {% endif %}
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" name="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div>
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="{% url 'accounts:password_reset' %}">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'accounts:register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'expense_tracker_app/base.html' %}
{% load static %}
{% block title %}Password Change{% endblock %}
{% block active_page %}Password Change{% endblock %}
{% block header_title %}Password Change{% endblock %}
{% block content %}
<div class="row">
  <div class="col-5">
    <div class="card card-success card-outline">
      <form method="post" class="form-horizontal">
      {% csrf_token %}
        <div class="card-body">
          <p>Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.</p>
          <div class="form-group row">
            <label class="col-form-label col-xl-3" for="id_old_password">Old password:</label>
            <div class="col-xl-7">
              <input class="form-control" type="password" name="old_password" id="id_old_password">
            </div>
          </div>
          {% if form.old_password.errors %}
            {% for error in form.old_password.errors %}
              <div class="row">
                <div class="col-12 text-danger">
                  {{ error }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
          <!-- /.form-group -->
          <div class="form-group row">
            <label class="col-form-label col-xl-3" for="id_new_password1">New password:</label>
            <div class="col-xl-7">
              <input class="form-control" type="password" name="new_password1" id="id_new_password1">
            </div>
          </div>
          <!-- /.form-group -->
          <div class="form-group row">
            <label class="col-form-label col-xl-3" for="id_new_password2">New password:</label>
            <div class="col-xl-7">
              <input class="form-control" type="password" name="new_password2" id="id_new_password2">
            </div>
          </div>
          {% if form.new_password2.errors %}
            {% for error in form.new_password2.errors %}
              <div class="row">
                <div class="col-12 text-danger">
                  {{ error }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <div class="row">
              <div class="col-12">
                {{ message }}
              </div>
            </div>
            {% endfor %}
          </ul>
          {% endif %}
          <!-- /.form-group -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          <button type="submit" class="btn btn-secondary">Change password</button>
        </div>
        <!-- /.card-footer -->
      </form>
    </div>
    <!-- /.card -->
  </div>
  <!-- /.col -->
</div>
<!-- /.row -->
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block page_title %}Password Reset Complete{% endblock %}
{% block body %}
<body class="login-page" style="min-height: 348.8px;">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index' %}"><b>Expense</b>Tracker</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p>Your password has been reset. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now</p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block page_title %}Password Reset Confrimation{% endblock %}
{% block body %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index' %}"><b>Expense </b>Tracker</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Please enter your new password twice so we can verify you typed it in correctly.</p>

      <form method="post">
        {% csrf_token %}
        <input style="display: none;" autocomplete="username" value="{{ form.user.username }}">
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="New password" id="new_password1" name="new_password1">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Confirm password" id="new_password2" name="new_password2">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        {% if form.new_password2.errors %}
          {% for error in form.new_password2.errors %}
          <div class="row">
            <div class="col-12 text-danger">
              {{ error }}
            </div>
          </div>
          {% endfor %}
        {% endif %}
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
          <div class="row">
            <div class="col-12 text-danger">
              {{ error }}
            </div>
          </div>
          {% endfor %}
        {% endif %}
          <div class="row">
            <button type="submit" class="btn btn-primary btn-block">Change my password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block page_title %}Password Reset Done{% endblock %}
{% block body %}
<body class="login-page" style="min-height: 348.8px;">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index' %}"><b>Expense</b>Tracker</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <h1>Check your inbox.</h1>
      <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} Expense Tracker Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Expense Tracker Team
{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block page_title %}Password Reset{% endblock %}
{% block body %}
<body class="login-page" style="min-height: 348.8px;">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'index' %}"><b>Expense</b>Tracker</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>
      <form method="POST">
      {% csrf_token %}
        <div class="input-group mb-3">
          <input type="email" class="form-control" id="id_email" required="true" name="email" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="{% url 'accounts:login' %}">Login</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'accounts:register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block page_title %}Registration Page{% endblock %}
{% block body %}
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href="{% url 'index' %}"><b>Expense </b>Tracker</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form action="" method="post">
      {% csrf_token %}
        <div class="input-group mb-3">
          {% render_field form.username class="form-control" placeholder="Username" %}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        {% if form.username.errors %}
          {% for error in form.username.errors %}
            <div class="row">
              <div class="col-12 text-danger">
                {{ error }}
              </div>
            </div>
          {% endfor %}
        {% endif %}
        <div class="input-group mb-3">
          {% render_field form.email class="form-control" placeholder="Email" %}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        {% if form.email.errors %}
          {% for error in form.email.errors %}
            <div class="row">
              <div class="col-12 text-danger">
                {{ error }}
              </div>
            </div>
          {% endfor %}
        {% endif %}
        <div class="input-group mb-3">
          {% render_field form.password1 class="form-control" placeholder="Password" %}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        {% if form.password1.errors %}
            {% for error in form.password1.errors %}
              <div class="row">
                <div class="col-12 text-danger">
                  {{ error }}
                </div>
              </div>
            {% endfor %}
          {% endif %}
        <div class="input-group mb-3">
          {% render_field form.password2 class="form-control" placeholder="Retype password" %}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        {% if form.password2.errors %}
          {% for error in form.password2.errors %}
            <div class="row">
              <div class="col-12 text-danger">
                {{ error }}
              </div>
            </div>
          {% endfor %}
        {% endif %}
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
          <div class="row">
            <div class="col-12 text-danger">
              ss{{ error }}
            </div>
          </div>
          {% endfor %}
        {% endif %}
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              {% render_field form.terms %}
              <label for="id_terms">
                I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
        {% if form.terms.errors %}
          {% for error in form.terms.errors %}
          <div class="row">
            <div class="col-12 text-danger">
              {{ error }}
            </div>
          </div>
          {% endfor %}
        {% endif %}
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <div class="row">
            <div class="col-12">
              {{ message }}
            </div>
          </div>
          {% endfor %}
        </ul>
        {% endif %}
      </form>
      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div>
      <a href="{% url 'accounts:login' %}" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->
{% endblock %}